name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@v0.0.11
      with:
        start-args: '--driver docker --profile spowell'
    - name: kubectl
      run: kubectl get pods -A
