name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: macos-12
    name: job1
    steps:
    - name: start minikube
      continue-on-error: true
      id: minikube
      uses: medyagh/setup-minikube@v0.0.11
      with:
        start-args: '--alsologtostderr'
    - run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
        chmod +x ./minikube-darwin-amd64
        ./minikube-darwin-amd64 ssh -- sudo systemctl status cri-docker.service --no-pager -l
        ./minikube-darwin-amd64 ssh -- sudo journalctl -u cri-docker.service --no-pager
        ./minikube-darwin-amd64 ssh -- sudo systemctl status cri-docker.socket --no-pager -l
        ./minikube-darwin-amd64 ssh -- sudo journalctl -u cri-docker.socket --no-pager
